// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewCardGame.Data;

#nullable disable

namespace NewCardGame.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NewCardGame.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ItsOK")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d936ec3a-6e43-4558-88d9-775d934667c7"),
                            ItsOK = false,
                            Name = "ace clubs",
                            Suit = "C",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("236ba3d4-2d1d-4a9d-a4d5-01f94b6364bd"),
                            ItsOK = false,
                            Name = "two clubs",
                            Suit = "C",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("1dcbcf94-11a0-45b8-b8fa-301303bb8597"),
                            ItsOK = false,
                            Name = "three clubs",
                            Suit = "C",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("f1883297-e207-4818-a2ed-70b6ea208323"),
                            ItsOK = false,
                            Name = "four clubs",
                            Suit = "C",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("d0b27ce1-5b43-4a2a-b2fb-7288824a4d85"),
                            ItsOK = false,
                            Name = "five clubs",
                            Suit = "C",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("e5445d3d-5152-4163-a18b-16f6576e3ecd"),
                            ItsOK = false,
                            Name = "six clubs",
                            Suit = "C",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("38c94d1c-77a4-4905-a6be-3cbab449dc8e"),
                            ItsOK = false,
                            Name = "seven clubs",
                            Suit = "C",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("0c9eafe8-796c-47f8-a2c4-98b1ed6b8594"),
                            ItsOK = false,
                            Name = "eight clubs",
                            Suit = "C",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("53166a74-02a2-453d-9008-e663878646c1"),
                            ItsOK = false,
                            Name = "nine clubs",
                            Suit = "C",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("668a3a70-3017-486c-9f69-81f9bd63f4a0"),
                            ItsOK = false,
                            Name = "ten clubs",
                            Suit = "C",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("1f5873d4-d3cf-45c5-8eb0-9c5522bcce7b"),
                            ItsOK = false,
                            Name = "jack clubs",
                            Suit = "C",
                            Value = 11
                        },
                        new
                        {
                            Id = new Guid("c856f539-4e1e-42e4-b6e2-dd88b0df8f04"),
                            ItsOK = false,
                            Name = "queen clubs",
                            Suit = "C",
                            Value = 12
                        },
                        new
                        {
                            Id = new Guid("131531af-4780-4353-89f9-4bd912acaea2"),
                            ItsOK = false,
                            Name = "king clubs",
                            Suit = "C",
                            Value = 13
                        },
                        new
                        {
                            Id = new Guid("17260e2c-29e1-40d5-8644-9fb90550c846"),
                            ItsOK = false,
                            Name = "king hearts",
                            Suit = "H",
                            Value = 13
                        },
                        new
                        {
                            Id = new Guid("1affa909-0d49-4416-bd36-1755174b4d44"),
                            ItsOK = false,
                            Name = "ten spades",
                            Suit = "S",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("002e8179-dae8-48e0-90d0-98616ac415ad"),
                            ItsOK = false,
                            Name = "ten diamonds",
                            Suit = "D",
                            Value = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
